[profile.default]
src = 'contracts'
out = 'out'
libs = [
    'lib'
]
ffi=true
verbosity=5
[rpc_endpoints]
mainnet = "${rpc}"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config